### ISSUE TITLE
Extend travel probabilities for public transport

### ISSUE THREAD

**Issue by Sipke82** [algernon-A/Lifecycle-Rebalance-Revisited#11]
Add the possibility to define more precise travel probabilities, mainly for public transport so we can differentiate based on wealth level on the various public transport types such us; bus, train, ferry, helicopter, etc.
A nice addition might be actual impact of the ticket price?

**Comment by algernon-A** [comment]
After investigation, have confirmed that this is not feasible for this mod.  Would have to be part of a comprehensive 'public transport overhaul' mod.
