### ISSUE TITLE
Pre compiled package for non Steam version?

### ISSUE THREAD

**Issue by Geobert** [algernon-A/Lifecycle-Rebalance-Revisited#15]
Hi,

Happy new year and thank you for your mod!

Would it be possible to release a precompiled version here on GitHub for those who use the game without Steam (Epic) please?

Thanks

**Comment by algernon-A** [comment]
Yes, I'll look at doing so - once the upcoming 1.5.2 release is out (about to release for testing shortly).

**Comment by Geobert** [comment]
Thank you very much for considering it!

**Comment by algernon-A** [comment]
Completed for 1.5.2 - see [releases](https://github.com/algernon-A/Lifecycle-Rebalance-Revisited/releases).
